apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: student-<NUMBER>-jenkins
  namespace: argocd
spec:
  project: default
  destination:
    namespace: student-7
    name: in-cluster
  syncPolicy:
    automated: {}
  sources:
    - repoURL: 'https://charts.bitnami.com/bitnami'
      targetRevision: 12.4.0
      helm:
        valueFiles:
          - $values/jenkins/values.yaml
      chart: jenkins
    - repoURL: 'https://github.com/Dzoge/argocd-katas'
      targetRevision: main
      ref: values
